framework:
    default_locale: '%locale%'
    translator:
        default_path: '%kernel.project_dir%/vendor/shopware/platform/src/Storefront/Snippet'
        fallbacks:
            - 'en_GB'
            - 'en'